apiVersion: v1
kind: ConfigMap
metadata:
  name: heart-disease-api-config
  labels:
    app: heart-disease-api
data:
  LOG_LEVEL: "info"
  WORKERS: "2"
  API_VERSION: "1.0.0"
  MODEL_PATH: "/app/models"
  MAX_PREDICTION_BATCH_SIZE: "100"
